version: '3.8'

services:
  # Development environment
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    